module.exports = {
  '!addtask': require('./task'),
  '!buildraidmsg': require('./buildraidmsg'),
  '!done': require('./done'),
  '!edittask': require('./edittask'),
  '!give': require('./give'),
  '!guess': require('./ttol'),
  '!leaderboard': require('./leaderboard'),
  '!pawggers': require('./pawggers'),
  '!removetask': require('./removetask'),
  '!take': require('./take'),
  '!taskadd': require('./task'),
  '!taska': require('./task'),
  '!taskedit': require('./edittask'),
  '!taskd': require('./done'),
  '!taskdone': require('./done'),
  '!ttol': require('./ttol'),
  '!ttolanswer': require('./ttolend'),
  '!ttolend': require('./ttolend'),
  '!ttolstart': require('./ttolstart'),
};
