const database = require('../database');
const discord = require('../managers/discord');

// every day at 11am post a journaling prompt message

const startJournalPromptJob = function() {
  let journalingTable = database.get('journaling');
  journalingTable = journalingTable || {};

  const { lastPromptAt } = journalingTable;
  const nextPromptAt = getNextPromptAt(lastPromptAt);
  const now = new Date();
  if (now >= nextPromptAt) {
    sendPrompt();
    return;
  }

  setTimeout(sendPrompt, nextPromptAt - now);
};

function getNextPromptAt(lastPromptAt) {
  if (!lastPromptAt) {
    return getNext11am();
  } else {
    const lastPromptTime = new Date(lastPromptAt);
    const next11am = new Date(lastPromptTime);
    next11am.setDate(next11am.getDate() + 1);
    next11am.setHours(11, 0, 0, 0);
    return next11am;
  }
}

function getNext11am() {
  const now = new Date();
  const etNow = now.toLocaleString("en-US", { timeZone: "America/New_York" });
  const next11am = new Date(etNow);
  next11am.setHours(11, 0, 0, 0);

  if (now > next11am) {
    next11am.setDate(next11am.getDate() + 1);
    // in case tomorrow is DST transition
    next11am.setHours(11, 0, 0, 0);
  }

  return next11am;
}

function sendPrompt() {
  let journalingTable = database.get('journaling');
  journalingTable = journalingTable || {};
  const { lastPromptIndex } = journalingTable;

  let promptIndex;
  do {
    promptIndex = Math.floor(Prompts.length * Math.random())
  } while (promptIndex === lastPromptIndex);

  journalingTable.lastPromptIndex = promptIndex;
  journalingTable.lastPromptAt = new Date();
  database.set('journaling', journalingTable);

  discord.sendMessage('journaling', `Today's journal prompt is:\n**${Prompts[promptIndex]}**`);

  startJournalPromptJob();
}

module.exports = startJournalPromptJob;

const Prompts = [
  "Reflect on something that used to be hard for you.",
  "How could you add more fun or play into your life?",
  "Take a roadblock in your life right now and ask the question, “What would this look like if it were easy?”",
  "Write a letter of support to someone that you care about. This can be someone you actually know or someone that you have never actually met. You don’t need to send them the letter.",
  "Analyze a victory. Think of something that you did well and break down the active ingredients that allowed you to kick ass in that situation.",
  "Take a task that you’ve been dreading and break it up into the smallest possible steps.",
  "What is your metric for success right now? What would you like to judge yourself based on?",
  "Mentally walk through your day and identify ways you could change your environment to make things easier or smoother.",
  "What is a view about the world that has changed for you as you’ve gotten older?",
  "What is your first memory?",
  "How did your parents try to influence or control your behavior?",
  "List 5 things that you have enjoyed in the past. List 5 things that other people do that seem like they would be fun to try.",
  "Write about something you would like to forgive yourself for.",
  "What are some things that you judge others for that you would NEVER judge yourself for?",
  "Figure out where you do your best thinking and see how you can spend more time there.",
  "How would you like to be remembered?",
  "What are some qualities that you admire in others? In what small ways can you integrate more of those into your life?",
  "Think about a “what if?” or worst-case scenario and work your way through the problem, identifying your options to get through it if it were to happen.",
  "What kind of friend could you use right now?",
  "How have you changed in the last year?",
  "What are some positive things that you have taken away from the family culture you were raised in?",
  "If you could live one other person’s life, whose and why?",
  "What would be different about your life if you lived 100 years from now?",
  "If you could choose another career, vocation, or field of study than you have, what would it be and why?",
  "What were the best and worst parts about your adolescence?",
  "If you could re-do a decade of your life, which would you re-do and why?",
  "What relatives have you felt closest to?",
  "Who is the most difficult person in your life and why?",
  "How do you feel about the place that you grew up in? Would you change it?",
  "What are some small things that other people have done that really make your day?",
  "Pull a random book from the closest shelf/pile and flip to a random page. Try to find a way that the words (or numbers or pictures) on the page apply to your life right now. No cheating.",
  "How did you like having fun as a kid. Has any of that carried over into adulthood?",
  "What is a made-up rule about your life that you are applying to yourself? How has this held you back and how might you change it?",
  "What is a value of yours that you are not spending as much time as you would like on?",
  "What is something you don’t value that you are spending TOO much time on?",
  "How do you feel toward other people that you know have anxiety?",
  "What would be a “force multiplier” skill or habit that you could work on, which would make all the other things you are doing with your life just a bit easier?",
  "Write about something that you would like to let go of.",
  "List 20 things that make you happy.",
  "Write some lyrics to a favorite song and reflect on why they resonate with you so much.",
  "Make a doodle using only basic geometric shapes like lines, rectangles, circles, triangles etc.",
  "Which areas in your life do you have the most control and which do you have the least?",
  "Write about a mistake that taught you something about yourself.",
  "Write a letter to your 9-year-old self.",
  "Write a letter to your 13-year-old self.",
  "Write a letter to your 18-year-old self.",
  "Write a letter to yourself 5 years ago.",
  "Write a letter to yourself 10 years from now.",
  "What is a reminder that you would like to tell yourself next time you are in an anxious spiral?",
  "Who have you genuinely helped in your life?",
  "Who has been your greatest teacher?",
  "Describe your upbringing as you understand it today.",
  "What do you wish more people knew about you?",
  "What fictional character do you most identify with and why?",
  "Write 10 qualities that you appreciate in yourself (push yourself to get to 10) and 2 that you’d like to change or work on.",
  "What is your relationship to spirituality? Has that changed over time?",
  "How did your parents deal with adversity?",
  "What small thing are you actually really proud of? Why does this mean so much to you?",
  "What do people get wrong about you?",
  "If you were to give your anxiety a name, what would it be and why?",
  "What images from your past (if any) make you feel safest? If none do, why not?",
  "Write about your happiest childhood memory.",
  "If you had to go on stage and sing one song without making any mistakes, which would you pick? Prove it. Write all the lyrics to that song without looking them up.",
  "Write a bit about physical pain and how it impacts your life and mood.",
  "What are 5-10 of the most important aspects of your identity?",
  "Do you truly hate anyone? Who and why?",
  "What are your attitudes and opinions about therapy?",
  "What are your attitudes and opinions about medication?",
  "Who were your models of love and affection? What did you learn from them?",
  "Which quotes or pieces of advice do you have committed to memory? Why have those stuck with you?",
  "What are 5-10 things that your parents don’t know about you?",
  "If you had $500 to spend with no regrets, how would you use it to make your most perfect day?",
  "What are some things that you could invest more money in to make life smoother and easier for yourself?",
  "Write about a dream that you can remember from the past. What does this dream mean to you now?",
  "Write about 3 ways that anxiety has helped you in the past.",
  "Practice a call or conversation that you are avoiding. Write out both sides of the roleplay from start to finish.",
  "Which emotion is most difficult for you to experience and why?",
  "What are some of the self-fulfilling prophecies that have played out in your life?",
  "What are a few ways that you could use the evening to set yourself up for success the next day?",
  "What are you looking forward to right now?",
  "What is the best compliment that you have ever received?",
  "How do you take praise? How do you take criticism?",
  "What’s an indulgence that you haven’t let yourself partake in recently?",
  "Close your eyes and imagine yourself somewhere safe. Describe the place that came to mind and reflect on what felt safe about it.",
  "What are some of the worst pieces of advice that you have gotten?",
  "What are some simple tweaks that you can make to your environment to reduce anxiety?",
  "If you could know one thing about the future what would it be?",
  "What is a chance that you have taken that paid off in the end?",
  "Assign a role (like peacekeeper, joker, or golden child) to each of your immediate family members.",
  "List 10 things that make you smile.",
  "Build a list of 10-15 songs that you can use to change your mood for the better.",
  "Build a list of 5 videos that you can watch when you need motivation.",
  "When was the last time you had to hold your tongue? What would you want to say if you didn’t have to?",
  "Who is somebody that you miss? Why?",
  "Where in your body do you feel your anxiety? What is the first hint that anxiety is coming on?",
  "What would you like to be able to say “no” to more often?",
  "What is a boundary that you need to draw in your life?",
  "What activities make you enter a “flow” state and totally lose track of time? Are there any that you could integrate more of into your life now?",
  "Try to write your full name with your non-dominant hand. Keep practicing until you fill up the page.",
  "What are your strongest sense memories?",
  "How do you feel about your job, current area of study, etc?",
  "Consider a misfortune or roadblock in your life right now. Ask yourself, “Whatdoes this allow me to do?”",
  "Are you taking enough risks in your life? Would you like to change your relationship to risk? If so, how?",
  "At what point in your life have you had the highest self-esteem?",
  "Consider and reflect on what might be your “favorite failure.”",
  "Draw 25 circles on a page (5x5 grid of circles). Now set a timer for 3 minutes and try to turn each one into something unique. Could be a ball, hand cuffs, a logo, or an eye for instance.",
  "Draw a small scribble on the page then use your imagination to turn that scribble into a full drawing.",
  "Find two unrelated objects near you and think of a clever way they might be used together.",
  "How can you reframe one of your biggest regrets in life?",
  "How did you bond with one of the best friends you’ve ever had?",
  "How did your parents or caregivers try to influence or control your behavior when you were growing up?",
  "How do the opinions of others affect you?",
  "How do you feel about asking for help?",
  "How much do your current goals reflect your desires vs someone else’s?",
  "If you could eliminate any one disease or illness from the world, what would you choose and why?",
  "Imagine that you have arrived at a closed door. What does it look like and what’s on the other side?",
  "In what ways are you currently self-sabotaging or holding yourself back?",
  "Invent your own planet. Draw a rough sketch of the planet and its inhabitants. How is it different than Earth?",
  "React to the following quote from Anaïs Nin: “We don't see things as they are, we see them as we are.”",
  "React to the following quote from We All Looked Up by Tommy Wallach: “Do you think it is better to fail at something worthwhile, or to succeed at something meaningless?”",
  "Take a task that you’ve been dreading and break it up into the smallest possible steps.",
  "Talk about a time that you are proud to have told someone “no.”",
  "The world would be a lot better if…",
  "Think about a “what if?” or worst-case scenario and work your way through the problem, identifying your options to get through it if it were to happen.",
  "Think about the last time you cried. If those tears could talk, what would they have said?",
  "What are some small things that other people have done that really make your day?",
  "What are some things that frustrate you? Can you find any values that explain why they bug you so much?",
  "What are some things that you could invest more money in to make life smoother and easier for yourself?",
  "What biases do you need to work on?",
  "What could you do to make your life more meaningful?",
  "What did you learn from your last relationship? If you haven’t had one, what could you learn from a relationship that you’ve observed?",
  "What do you need to give yourself more credit for?",
  "What do you wish you could do more quickly? What do you wish you could do more slowly?",
  "What does “ready” feel like to you? How did you know you were ready for a major step that you have taken in your life?",
  "What happens when you are angry?",
  "What is a boundary that you need to draw in your life?",
  "What is a made-up rule about your life that you are applying to yourself? How has this held you back and how might you change it?",
  "What is a positive habit that you would really like to cultivate? Why and how could you get started?",
  "What is a question that you are really scared to know the answer to?",
  "What is a reminder that you would like to tell yourself next time you are in a downward spiral?",
  "What is a view about the world that has changed for you as you’ve gotten older?",
  "What is holding you back from being more productive at the moment? What can you do about that?",
  "What is something that you grew out of that meant a lot to you at the time?",
  "What is something that you have a hard time being honest about, even to those you trust the most? Why?",
  "What life lessons, advice, or habits have you picked up from fiction books?",
  "What made you feel most alive when you were young?",
  "What part of your work do you most enjoy? What part do you least enjoy? Why?",
  "What pet peeves do you have? Any idea why they drive you so crazy?",
  "What sensations or experience do you tend to avoid in your life? Why?",
  "What was a seemingly inconsequential decision that made a big impact in your life?",
  "What would you do if you could stop time for two months?",
  "When was the last time you had to hold your tongue? What would you have said if you didn't have to?",
  "Which emotions in others do you have a difficult time being around? Why?",
  "Which quotes or pieces of advice do you have committed to memory? Why have those stuck with you?",
  "Which songs have vivid memories for you?",
  "Who has been your greatest teacher?",
  "Who is somebody that you miss? Why?",
  "Who is the most difficult person in your life and why?",
  "Why do you dress the way that you do?",
  "Write a complete story with just six words. For example: Turns out the pain was temporary.",
  "Write a letter to someone you miss dearly.",
  "Write a letter to your own body, thanking it for something amazing it has done.",
  "Write a thank you note to someone. Sending is optional.",
  "Write about a mistake that taught you something about yourself.",
  "Write about an aspect of your personality that you appreciate in other people as well.",
  "Write about something (or someone) that is currently tempting you.",
  "Write about something that you would like to let go of.",
  "Write an apology to yourself for a time you treated yourself poorly. Remember, a good apology should feature an acknowledgment of what happened, how it made the person feel, and how you will do better in the future.",
  "You have been temporarily blinded by a bright light. When your vision clears, what do you see?",
  "First, list five words that best describe you. Then, think about which five words you would like to describe yourself.",
  "Complete this sentence: “My life would be incomplete without….”",
  "Reflect on a phrase, quote, or mantra that resonates with you. Explain why it’s significant to you.",
  "Make a list of the things in your life that you’re most grateful for.",
  "Explain what you do best.",
  "Reflect on the qualities that you value most in others.",
  "Share three things that made you smile today.",
  "List your best and worst habits.",
  "Write down three life lessons you’ve learned.",
  "Explain what love means to you.",
  "Describe the values that are most important to you and consider whether your actions align with them.",
  "Think about what you would do with your life if you had unlimited resources and explain why.",
  "Describe what is stressing you out and how you’re coping with it.",
  "Write about your biggest regret and what you would do differently in hindsight.",
  "Identify and label the fears and insecurities that are holding you back right now.",
  "What are three short-term goals you would like to achieve within the next three months?",
  "What are three long-term goals you would like to achieve within the next five years?",
  "Which skill would you like to cultivate in yourself?",
  "Which qualities do you admire most in others that you would like to develop in yourself?",
  "Which areas of your life would benefit from more self-discipline?",
  "What is your worst habit and how would you change it?",
  "What’s something new you would like to try?",
  "What habit do you want to add to your daily routine?",
  "What would you like to contribute to your community?",
  "What is the biggest challenge you’re dealing with right now?",
  "What is the biggest failure you’ve ever faced and what have you learned from it?",
  "How would you like to be remembered by others?",
  "How can you better support your loved ones?",
  "What boundaries would you like to set in your relationships to protect yourself?",
  "Describe a meal you ate today. What colors, textures, tastes, and feelings did you experience?",
  "Pick an everyday object from your surroundings, like a plant or a pencil. Write a detailed description of it as if you've never seen it before.",
  "Focus on a sound in the background, such as the ticking of a clock or the rustling of the breeze. Describe the sound and its impact on you.",
  "Close your eyes for a minute and pay attention to your breath. When you open your eyes, write down what it felt like.",
  "Describe your ideal day from morning to night. What activities, people, and experiences would be part of it?",
  "Reflect on your thoughts without judgment. Identify and describe any feelings you're experiencing in the present moment.",
  "Write about a recent interaction with someone. What were their words, expressions, and gestures? How did you feel during the interaction?",
  "Think back to a moment of happiness you experienced recently. Relive the sensations, thoughts, and emotions associated with it.",
  "Think about the place where you feel most at peace. What makes it special to you?",
  "Recall a time when you were worrying about something in the future. How did it affect your present moment and what would you have done differently?",
  "Write a letter to your favorite fictional character, describing your life to them.",
  "Make a list of questions you would like to ask a future version of yourself.",
  "Think about your favorite word or phrase. Explain why you love it.",
  "Choose a random object from your surroundings. What qualities do you have in common with it?",
  "Make a list of ten unusual ways to use a common household item. Get creative and think outside the box.",
  "Write a conversation between two inanimate objects, giving them personalities and voices.",
  "Invent a gadget that would make your life more efficient or interesting.",
  "Choose a word from a foreign language that doesn't have a direct English translation. Describe the last time you encountered or experienced it.",
  "Imagine you get the chance to be any animal for a day. Which animal would you pick and what would you do?",
  "Invent a new holiday and outline the traditions, celebrations, and rituals associated with it, based on your values.",
  "If you have a time machine and you can go anywhere in the past or future, where would you go and what would you do there?",
  "Write down 5 things that make you incredibly happy and describe why they make you feel this way.",
  "What do you fear the most? Why? Is your fear rational?",
  "What qualities about yourself do you love the most?",
  "In the next year, what are 5 improvements you would like to make regarding your life? Write about the improvements and create a plan to accomplish each one.",
  "Write about your one of your happiest memories?",
  "Write about the people in your life that make you feel the most “at ease” and what they do to make you feel that way.",
  "Write about a difficult memory and the coping mechanisms you used at the time. Would you change the way you dealt? How?",
  "Write a poem (that DOESN’T HAVE TO RHYME), describing the exact opposite of yourself.",
  "Write about the last time you cried. What caused you to cry?",
  "Write about the last time you laughed really hard. What was so funny?",
  "Write a letter to the future YOU.",
  "Write a letter to one of your parents – even if you don’t actually give it to them.",
  "What has your anxiety taught you about yourself?",
  "Write down a list of ‘regrets’. Either throw them away or toss them into a fire. (Let go of past regrets & move on).",
  "In detail, describe a perfect day.",
  "Write a letter to a person who has negatively impacted you. (Again, you don’t actually have to send it out).",
  "Write a letter to a person who has positively impacted you.",
  "Write about an incredibly difficult choice you’ve had to make in your life.",
  "Write down all your coping mechanisms. Evaluate the ones that are most helpful and the ones that are the most detrimental. ",
  "Describe what love means to you in detail.",
  "Write a letter of forgiveness to yourself.",
  "Write down 3 of your favorite smells. Describe, in detail, how each one makes you feel.",
  "Have you ever felt isolated? Write about it.",
  "Write about 5 songs that mean the most to you. Why do the lyrics speak to you? How do you relate to these songs? How do they make you feel when you hear them?",
  "Write down all the compliments you can think of, that you’ve received. Write down compliments to people in your life.",
  "Write a list of 10 things you want to remember during difficult times. (Use this later if you’re feeling down). ",
  "What risks do you want to take? What’s holding you back?",
  "What element do you consider to be YOU? Write about why. (Earth, Air, Fire, Water).",
  "What are some of the strongest emotions you’ve ever felt? Write about how those emotions affected you and what caused you to feel those emotions.",
  "Physically, how do you feel right now?",
  "What speaks to you on an spiritual level? (Poetry, quote, song ect.) Write about it.",
  "What items/objects do you find the most comforting? Why do you think that is? What is comforting about them?",
  "Write a love letter to yourself.",
  "Write about something that is frustrating to you.",
  "If you could be anywhere in the world at this very moment, where would you want to be and why?",
  "What are 3 things that make you angry? Why?",
  "What activities do you think would make you feel better? Make a plan to carry out those activities.",
  "Write about something random you’ve seen that made you smile.",
  "Describe your dream house.",
  "Who or what (or both), helps motivate you the most? Why is that?",
  "What are you worried about? Why?",
  "What are some of your favorite books? Why? Write about them.",
  "What makes you laugh?",
  "Write about what you perceive to be the worst thing you’ve ever done.",
  "When is the last time you did something for someone else? What did you do and how did it make you feel?",
  "What secrets are you keeping? Are these secrets affecting your life or mental health? Why or why not?",
  "Write about something that truly surprised you.",
  "Describe an outfit that makes you feel completely comfortable in your own skin. ",
  "If you weren’t afraid, what are 5 things you would do? Are there any ways you can think of to overcome the fear?",
  "Write a letter of forgiveness to someone who has caused you pain.",
  "How would you spend your perfect day off? What makes that perfect for you?",
  "Describe yourself in ten words. Why do those words come to mind?",
  "What makes you feel the most inspired?",
  "What is your favorite form of self-care? Why?",
  "What can you do today to take better care of yourself?",
  "What comes to mind first when you think of what makes you feel safe?",
  "What are five things about yourself you want people to know?",
  "What’s something that makes you feel warm inside?",
  "Explain what’s hardest for you in as many words as it takes.",
  "If you were to improve something about your life, what would that be? Why?",
  "What’s your first coping mechanism that comes to mind? Do you think it’s helpful or harmful, and why?",
  "How are you helping yourself when things are hard?",
  "Write a letter to your younger self, talking about mental health. What would you want to tell them?",
  "Do you allow yourself to feel the emotions you need to feel? Why or why not?",
  "What do you think is holding you back?",
  "Write a list of 10 things you want to be able to remember during your most difficult times.",
  "Which of the four elements (Earth, Air, Water, Fire) do you identify with? Explain why.",
  "Write a love letter to yourself.",
  "Describe an outfit that makes you feel entirely comfortable in your skin.",
  "Write a letter of forgiveness to someone who has caused you pain, including yourself.",
  "How are you feeling in this moment? Describe all that you are experiencing within yourself.",
  "What do you need in your life right now?",
  "What is something that you're grateful for today, and why?",
  "Write down three things that you accomplished this week, no matter how small they may seem.",
  "Write about a song that always comforts you. What do you like about it?",
  "What is something that you did today that made you feel happy or proud?",
  "What is something that you're struggling with right now, and what steps can you take to address it?",
  "Where do you feel most happy and relaxed?",
  "What is one part of your life that you won't trade for anything?",
  "Choose 3 people to say thanks today. Write about why you are thankful to them.",
  "What is your idea of a happy life?",
  "List 3 things that help you feel cozy and comfortable.",
  "What is a little thing that you can do to take care of yourself?",
  "Write about one positive change in your life from the last year.",
  "Write a letter to yourself, reflecting on your strengths and the progress you've made recently.",
  "Write down three things that you want to prioritize in your self-care routine this month.",
  "What is something that you can do today to show yourself some love and kindness?",
  "Write down five things that you're looking forward to in the next week or month.",
  "What is something that you're currently worrying about, and how can you reframe your thoughts to feel more positive and empowered?",
  "What is something that you're struggling with right now, and how can you show yourself kindness and compassion in this moment?",
  "Write about a time when you felt truly happy and content. What were the circumstances, and how can you recreate that feeling in your life now?",
  "Write a letter to yourself, reflecting on your current emotions and how you're coping with them. Be kind and compassionate to yourself as you write.",
  "What is something that you're afraid of or anxious about, and what steps can you take to address those feelings?",
  "Reflect on a recent event or experience that brought up strong emotions for you. Write about what you felt, why you felt it, and what you learned from the experience.",
  "What is something that you've been avoiding or putting off, and what is holding you back? How can you take a small step towards addressing it today?",
  "Write down three things that you're grateful for today, and why you appreciate them.",
  "Reflect on a time when you felt disappointed or let down by yourself or others. Write about what you learned from the experience and how you can use that knowledge moving forward.",
  "What is something that you're looking forward to in the near future, and why does it bring you joy and excitement?",
  "Reflect on a time when you overcame a difficult challenge, and write down what you learned from the experience.",
  "What is a quality in yourself that has helped you through the years?",
  "What is one thing that you can do for yourself today to promote self-care and positivity?",
  "What do you wish other people knew about you?",
  "Given the choice, where would you want to be right now?",
  "List 5 things in your bedroom that you are grateful for.",
  "Write a letter to your future self. What are your hopes for them?",
  "Write down three things that you love about yourself, and why they are important to you.",
  "Reflect on a time when you overcame a challenge or obstacle. What strengths and qualities did you draw upon, and how can you use them moving forward?",
  "Write about a person or experience that brings you joy and positivity. What do you appreciate about them, and how can you cultivate more of that feeling in your life?",
  "What is one small habit or routine that you can incorporate into your daily life to promote self-care and positivity?",
  "Write about a time when you felt proud of yourself or accomplished. What did you do to achieve that feeling, and how can you replicate it in other areas of your life?",
  "Reflect on a time when you gave yourself permission to rest and recharge. How did you feel afterwards, and how can you prioritize rest in your life moving forward?",
  "What is one thing that you can do today to show yourself kindness and compassion?",
  "Write down three things that you are grateful for in your life, and why they bring you positivity and joy.",
  "What is one positive affirmation or mantra that you can repeat to yourself throughout the day to promote positivity and self-care?",
  "Write about a time when you felt truly understood by someone. What did it feel like, and why was that experience important to you?",
  "Write a letter to yourself at a difficult time in your life, offering yourself compassion and understanding. What would you say to yourself now, with the benefit of hindsight and growth?",
  "Describe a place that feels particularly calming or peaceful to you.",
  "Reflect on a time when you felt truly passionate or inspired.",
  "Describe a moment in your life when you felt truly alive or present.",
  "Reflect on a time when you felt a strong sense of purpose or meaning in your life.",
  "Write about a time when you felt truly creative or innovative.",
  "What makes you feel calm?",
  "What makes you feel in control?",
  "What makes you feel powerful?",
  "How do you remind yourself that you're enough?",
  "How do you calm your nerves in a difficult situation?",
  "When do you feel happiest in your skin?",
  "If you were stranded on a desert island, what are the one thing and the one person you would choose to have with you and why?",
  "If you could relive an experience in your life, what would it be?",
  "What does growing older mean to you?",
  "Do you prefer to read fiction or non-fiction? Why?",
  "What do you love about your mind?",
  "What do you love about your body?",
  "What do you love about your personality?",
  "What are the 5 things that your past self would love about your current self?",
  "What is a challenge that you have overcome?",
  "What's one feeling that's been bothering you lately? How can you process and release it?",
  "What dream or desire have you been hesitant to pursue? What's holding you back, and what steps can you take to move towards it?",
  "What situation has been causing you stress or anxiety? How can you approach it in a way that aligns with your values and needs?",
  "When have you felt truly confident and empowered? How can you channel that energy into your current situation?",
  "When have you felt a strong connection to someone or something outside of yourself? How can you cultivate more of that connection in your life?",
  "When have you felt truly alive or present? How can you tap into that feeling again?",
  "When have you felt misunderstood or invalidated? How can you communicate your feelings and needs in a way that helps others understand you better?",
  "When have you experienced a significant loss or change in your life? What did you learn, and how can you use that knowledge to move forward?",
  "When have you felt truly vulnerable or exposed? How can you use that vulnerability to connect with others in a meaningful way?",
  "When have you felt truly seen and heard by someone else? How can you offer that same level of understanding and validation to others in your life?",
  "When have you felt a sense of shame or guilt? How can you release any negative feelings associated with that situation and move towards a place of healing and forgiveness?",
  "When have you felt a sense of purpose or meaning in your life? How can you use that sense of purpose to guide your decisions and actions moving forward?",
  "When have you felt truly grateful or appreciative? How can you cultivate more gratitude and appreciation in your life?",
  "When have you felt truly creative or innovative? How can you nurture your creativity and innovation in your daily life?",
  "When have you felt a strong sense of empathy or compassion for someone else? How can you cultivate those feelings of empathy and compassion in your daily life?",
  "When have you felt a strong connection to nature? How can you foster that connection in your daily life?",
  "What's one negative thought or belief you have about yourself? How can you challenge and reframe it in a more positive light?",
  "What's one activity or practice that always makes you feel better? How can you incorporate it more into your routine?",
  "What's one thing you've been avoiding that you know you need to confront? How can you take the first step towards confronting it?",
  "What's one thing you appreciate about yourself? How can you celebrate and honor that trait or quality in your life?",
  "What are your core values, and how do they guide your daily life and decision-making?",
  "Write about a recent situation in which you felt triggered or reactive. What was the trigger, and how did you react? What can you learn from this experience?",
  "What is your biggest fear, and how does it impact your behavior and decisions?",
  "Write about a time when you acted in a way that wasn't aligned with your values. What did you learn from the experience, and how can you act differently in the future?",
  "Reflect on a time when you felt most alive and engaged. What were you doing, and why did it bring you so much joy?",
  "Think about a time when you made a mistake. What went wrong? What do you think about it now?",
  "What is one belief or assumption that you hold about yourself or the world, and how does it shape your perspective and behavior?",
  "Write about a goal or aspiration that you have, and why it's important to you. What steps can you take to work towards that goal?",
  "What is one habit or behavior that you would like to change, and why is it important to you? How can you work towards making that change?",
  "Reflect on a relationship in your life that is important to you. What do you value about that relationship, and how can you nurture it?",
  "Write about a time when you faced a difficult decision. What factors did you consider, and how did you ultimately make the choice?",
  "What is one skill or trait that you admire in others, and why? How can you cultivate that quality in yourself?",
  "Write about a time when you received feedback that was difficult to hear. How did you react, and what did you learn from the experience?",
  "Reflect on a time when you felt judged or criticized. How did you respond, and what can you learn from that experience?",
  "Write about a time when you felt truly authentic and true to yourself. What did that feel like, and how can you cultivate that feeling in your daily life?",
  "What is one thing that you want to prioritize in your life moving forward, and why is it important to you? How can you take steps to make that priority a reality?",
];